### ISSUE TITLE
matlab code?

### ISSUE THREAD

**Issue by yanqswhu** [AIBluefisher/MVGPlus#1]
rewrite code from Matlab to c++?

**Comment by AIBluefisher** [comment]
Not exactly. I'm writing the code just for online teaching. Currently, the code would cover some basic algorithms of the MVG bible. In the future, I would also like to extend the implementations to some cutting-edge geometric algorithms that I'm interested in, such as perspective-n-point and ransac.

**Comment by yanqswhu** [comment]
Thank you for your contribution!
I can't wait to see your code.

MVG is the basis of 3D reconstruction, but it is difficult to really understand it from reading that boring book.
